### ISSUE TITLE
Add packages to Nixpkgs

### ISSUE THREAD

**Issue by garry-cairns** [FriendsOfOpenTelemetry/opentelemetry-nix#3]
Do you have any plans to add these packages such that they're available in nixpkgs? The collector and collector contrib are already available, but it would be good for the builder in particular to be available from there. If you don't intend to do so, do you have any objection to my using/adapting your nix code to do the same?

**Comment by gaelreyrol** [comment]
Hi @garry-cairns,

I do plan to backport the packages in nixpkgs, it just easier to add them here and tests them before submitting them in nixpkgs.
For the builder, I already thought about submitting it in nixpkgs but I don't know if its the purpose of nixpkgs to hold such code, I need to ask maintainers.

In the mean time what prevents you from using my repository or submit changes? What are your usages?

**Comment by garry-cairns** [comment]
No barrier to using your code at my end, and I'm doing so successfully without changes by adding it to my local nixpkgs fork. Thanks for putting it together, it's very helpful. I was only asking because, if there were no plans to add it in nixpkgs, I'd have been keen to do so.

Regarding the builder; I'd say it fits quite nicely in the current location for the collector and collector contrib (nixpkgs/pkgs/tools/misc/opentelemetry-collector/) as an additional nix file, say builder.nix. Having it there makes the development experience nicer for people wanting to contribute changes to the collectors while using nixOS on their machine.

**Comment by gaelreyrol** [comment]
@garry-cairns I totally agree, I don't have much time right now to submit the builder in Nixpkgs but I will look it as soon as I can work in it. In the mean time I will keep maintaining this builder here.

FIY I submitted a PR to add tracetest to Nixpkgs: https://github.com/NixOS/nixpkgs/pull/275406
